// Fraction questions and level configs for the Fractions Game

export const FRACTION_QUESTIONS = [
  // ─── IDENTIFY: Easy (halves & quarters) ───
  {
    id: "frac-1", type: "identify",
    question: "איזה שבר מתאר את החלק הצבוע?",
    visual: { total: 2, filled: 1, shape: "circle" },
    options: ["חצי", "רבע", "שליש", "שלם"],
    correct: 0,
    explanation: "חילקנו את העיגול ל-2 חלקים שווים וצבענו 1. זה חצי!",
    grades: [2, 3, 4], difficulty: "easy",
  },
  {
    id: "frac-2", type: "identify",
    question: "כמה חלקים צבועים מתוך כל החלקים?",
    visual: { total: 4, filled: 1, shape: "circle" },
    options: ["רבע", "חצי", "שליש", "שלושה רבעים"],
    correct: 0,
    explanation: "חילקנו ל-4 חלקים שווים וצבענו 1. זה רבע! (1 מתוך 4)",
    grades: [2, 3, 4], difficulty: "easy",
  },
  {
    id: "frac-3", type: "identify",
    question: "איזה שבר מתאר את החלק הצבוע?",
    visual: { total: 4, filled: 2, shape: "bar" },
    options: ["חצי", "רבע", "שלושה רבעים", "שליש"],
    correct: 0,
    explanation: "צבענו 2 מתוך 4 חלקים. 2/4 זה אותו דבר כמו חצי!",
    grades: [2, 3, 4], difficulty: "easy",
  },
  {
    id: "frac-4", type: "identify",
    question: "כמה חלקים צבועים מתוך כל החלקים?",
    visual: { total: 4, filled: 3, shape: "circle" },
    options: ["שלושה רבעים", "רבע", "חצי", "שליש"],
    correct: 0,
    explanation: "צבענו 3 מתוך 4 חלקים. זה שלושה רבעים! (3/4)",
    grades: [2, 3, 4], difficulty: "easy",
  },
  {
    id: "frac-5", type: "identify",
    question: "איזה שבר מתאר את החלק הצבוע?",
    visual: { total: 2, filled: 2, shape: "bar" },
    options: ["שלם", "חצי", "רבע", "שני שלישים"],
    correct: 0,
    explanation: "צבענו 2 מתוך 2 חלקים. כל החלקים צבועים - זה שלם!",
    grades: [2, 3, 4], difficulty: "easy",
  },
  {
    id: "frac-6", type: "identify",
    question: "כמה חלקים צבועים?",
    visual: { total: 4, filled: 2, shape: "circle" },
    options: ["2 מתוך 4", "1 מתוך 4", "3 מתוך 4", "1 מתוך 2"],
    correct: 0,
    explanation: "צבענו 2 חלקים מתוך 4 חלקים שווים.",
    grades: [2, 3, 4], difficulty: "easy",
  },
  {
    id: "frac-7", type: "identify",
    question: "איזה שבר מתאר את החלק הצבוע?",
    visual: { total: 2, filled: 1, shape: "bar" },
    options: ["חצי", "שלם", "רבע", "שליש"],
    correct: 0,
    explanation: "חילקנו ל-2 חלקים שווים וצבענו 1. זה חצי!",
    grades: [2, 3, 4], difficulty: "easy",
  },
  {
    id: "frac-8", type: "identify",
    question: "מה החלק הצבוע?",
    visual: { total: 4, filled: 4, shape: "bar" },
    options: ["שלם", "שלושה רבעים", "חצי", "רבע"],
    correct: 0,
    explanation: "כל 4 החלקים צבועים. זה שלם אחד!",
    grades: [2, 3, 4], difficulty: "easy",
  },

  // ─── IDENTIFY: Medium (thirds & fifths) ───
  {
    id: "frac-9", type: "identify",
    question: "איזה שבר מתאר את החלק הצבוע?",
    visual: { total: 3, filled: 1, shape: "circle" },
    options: ["שליש", "חצי", "רבע", "חומש"],
    correct: 0,
    explanation: "חילקנו ל-3 חלקים שווים וצבענו 1. זה שליש! (1/3)",
    grades: [2, 3, 4], difficulty: "medium",
  },
  {
    id: "frac-10", type: "identify",
    question: "כמה חלקים צבועים מתוך כל החלקים?",
    visual: { total: 3, filled: 2, shape: "bar" },
    options: ["שני שלישים", "שליש", "חצי", "שלושה רבעים"],
    correct: 0,
    explanation: "צבענו 2 מתוך 3 חלקים. זה שני שלישים! (2/3)",
    grades: [2, 3, 4], difficulty: "medium",
  },
  {
    id: "frac-11", type: "identify",
    question: "איזה שבר מתאר את החלק הצבוע?",
    visual: { total: 5, filled: 1, shape: "circle" },
    options: ["חומש", "רבע", "שליש", "חצי"],
    correct: 0,
    explanation: "חילקנו ל-5 חלקים שווים וצבענו 1. זה חומש! (1/5)",
    grades: [2, 3, 4], difficulty: "medium",
  },
  {
    id: "frac-12", type: "identify",
    question: "כמה חלקים צבועים?",
    visual: { total: 5, filled: 2, shape: "bar" },
    options: ["שני חומשים", "חומש", "חצי", "שני שלישים"],
    correct: 0,
    explanation: "צבענו 2 מתוך 5 חלקים. זה שני חומשים! (2/5)",
    grades: [2, 3, 4], difficulty: "medium",
  },
  {
    id: "frac-13", type: "identify",
    question: "איזה שבר מתאר את החלק הצבוע?",
    visual: { total: 5, filled: 3, shape: "circle" },
    options: ["שלושה חומשים", "שני חומשים", "שלושה רבעים", "שליש"],
    correct: 0,
    explanation: "צבענו 3 מתוך 5 חלקים. זה שלושה חומשים! (3/5)",
    grades: [3, 4], difficulty: "medium",
  },
  {
    id: "frac-14", type: "identify",
    question: "מה החלק הצבוע?",
    visual: { total: 3, filled: 3, shape: "circle" },
    options: ["שלם", "שני שלישים", "שליש", "שלושה רבעים"],
    correct: 0,
    explanation: "כל 3 החלקים צבועים. 3 מתוך 3 זה שלם!",
    grades: [2, 3, 4], difficulty: "medium",
  },
  {
    id: "frac-15", type: "identify",
    question: "איזה שבר מתאר את החלק הצבוע?",
    visual: { total: 5, filled: 4, shape: "bar" },
    options: ["ארבעה חומשים", "שלושה חומשים", "שלושה רבעים", "שני שלישים"],
    correct: 0,
    explanation: "צבענו 4 מתוך 5 חלקים. זה ארבעה חומשים! (4/5)",
    grades: [3, 4], difficulty: "medium",
  },

  // ─── COMPARE: Medium ───
  {
    id: "frac-16", type: "compare",
    question: "מה גדול יותר?",
    visual: {
      left: { total: 2, filled: 1, shape: "circle" },
      right: { total: 4, filled: 1, shape: "circle" },
    },
    options: ["חצי (1/2)", "רבע (1/4)", "שניהם שווים"],
    correct: 0,
    explanation: "חצי גדול יותר מרבע! חצי פיצה זה יותר מרבע פיצה.",
    grades: [3, 4], difficulty: "medium",
  },
  {
    id: "frac-17", type: "compare",
    question: "מה גדול יותר?",
    visual: {
      left: { total: 3, filled: 1, shape: "circle" },
      right: { total: 3, filled: 2, shape: "circle" },
    },
    options: ["שני שלישים (2/3)", "שליש (1/3)", "שניהם שווים"],
    correct: 0,
    explanation: "שני שלישים גדול יותר משליש! 2 חתיכות יותר מ-1.",
    grades: [3, 4], difficulty: "medium",
  },
  {
    id: "frac-18", type: "compare",
    question: "מה גדול יותר?",
    visual: {
      left: { total: 4, filled: 3, shape: "bar" },
      right: { total: 4, filled: 2, shape: "bar" },
    },
    options: ["שלושה רבעים (3/4)", "חצי (2/4)", "שניהם שווים"],
    correct: 0,
    explanation: "שלושה רבעים גדול מחצי! 3 חלקים מתוך 4 יותר מ-2 חלקים.",
    grades: [3, 4], difficulty: "medium",
  },
  {
    id: "frac-19", type: "compare",
    question: "מה גדול יותר?",
    visual: {
      left: { total: 4, filled: 2, shape: "circle" },
      right: { total: 2, filled: 1, shape: "circle" },
    },
    options: ["שניהם שווים!", "חצי (1/2)", "2 מתוך 4"],
    correct: 0,
    explanation: "2 מתוך 4 זה בדיוק כמו 1 מתוך 2. שניהם חצי!",
    grades: [3, 4], difficulty: "medium",
  },
  {
    id: "frac-20", type: "compare",
    question: "מה קטן יותר?",
    visual: {
      left: { total: 5, filled: 1, shape: "circle" },
      right: { total: 3, filled: 1, shape: "circle" },
    },
    options: ["חומש (1/5)", "שליש (1/3)", "שניהם שווים"],
    correct: 0,
    explanation: "חומש קטן משליש! ככל שמחלקים ליותר חלקים, כל חלק קטן יותר.",
    grades: [3, 4], difficulty: "medium",
  },
  {
    id: "frac-21", type: "compare",
    question: "מה גדול יותר?",
    visual: {
      left: { total: 5, filled: 3, shape: "bar" },
      right: { total: 5, filled: 2, shape: "bar" },
    },
    options: ["שלושה חומשים (3/5)", "שני חומשים (2/5)", "שניהם שווים"],
    correct: 0,
    explanation: "3 חלקים מתוך 5 גדול מ-2 חלקים מתוך 5!",
    grades: [3, 4], difficulty: "medium",
  },

  // ─── WORD PROBLEMS: Medium ───
  {
    id: "frac-22", type: "wordProblem",
    question: "אמא חתכה פיצה ל-4 חלקים שווים. דני אכל חלק אחד. איזה חלק מהפיצה דני אכל?",
    visual: { emoji: "\u{1F355}", parts: 4, filled: 1, context: "פיצה" },
    options: ["רבע", "חצי", "שליש", "שלושה רבעים"],
    correct: 0,
    explanation: "הפיצה חולקה ל-4 חלקים ודני אכל 1. הוא אכל רבע פיצה!",
    grades: [3, 4], difficulty: "medium",
  },
  {
    id: "frac-23", type: "wordProblem",
    question: "יש עוגה חתוכה ל-3 חלקים שווים. שרה אכלה 2 חלקים. כמה אכלה שרה?",
    visual: { emoji: "\u{1F370}", parts: 3, filled: 2, context: "עוגה" },
    options: ["שני שלישים", "שליש", "חצי", "שלושה רבעים"],
    correct: 0,
    explanation: "העוגה חולקה ל-3 ושרה אכלה 2 חלקים. זה שני שלישים!",
    grades: [3, 4], difficulty: "medium",
  },
  {
    id: "frac-24", type: "wordProblem",
    question: "בכיתה יש 5 ילדים. 2 מהם לובשים משקפיים. איזה חלק מהכיתה לובש משקפיים?",
    visual: { emoji: "\u{1F453}", parts: 5, filled: 2, context: "ילדים" },
    options: ["שני חומשים", "חומש", "חצי", "שני שלישים"],
    correct: 0,
    explanation: "2 מתוך 5 ילדים. זה שני חומשים! (2/5)",
    grades: [3, 4], difficulty: "medium",
  },
  {
    id: "frac-25", type: "wordProblem",
    question: "לנועה יש 2 תפוחים. היא נתנה תפוח אחד לחברה. איזה חלק מהתפוחים נתנה?",
    visual: { emoji: "\u{1F34E}", parts: 2, filled: 1, context: "תפוחים" },
    options: ["חצי", "רבע", "שליש", "שלם"],
    correct: 0,
    explanation: "נועה נתנה 1 מתוך 2 תפוחים. זה חצי!",
    grades: [2, 3, 4], difficulty: "medium",
  },

  // ─── HARD: Mixed challenge ───
  {
    id: "frac-26", type: "identify",
    question: "אם צבענו חצי מהעיגול, כמה חלקים צבועים אם העיגול חתוך ל-6?",
    visual: { total: 6, filled: 3, shape: "circle" },
    options: ["3", "2", "4", "1"],
    correct: 0,
    explanation: "חצי מ-6 זה 3! אם מחלקים ל-6 חלקים, חצי = 3 חלקים.",
    grades: [4], difficulty: "hard",
  },
  {
    id: "frac-27", type: "compare",
    question: "מה גדול יותר?",
    visual: {
      left: { total: 3, filled: 2, shape: "circle" },
      right: { total: 4, filled: 3, shape: "circle" },
    },
    options: ["שלושה רבעים (3/4)", "שני שלישים (2/3)", "שניהם שווים"],
    correct: 0,
    explanation: "3/4 = 0.75 ו-2/3 = 0.66. שלושה רבעים גדול יותר!",
    grades: [4], difficulty: "hard",
  },
  {
    id: "frac-28", type: "wordProblem",
    question: "אבא חתך עוגה ל-8 חלקים. המשפחה אכלה 6 חלקים. כמה נשאר?",
    visual: { emoji: "\u{1F382}", parts: 8, filled: 6, context: "עוגה" },
    options: ["רבע (2/8)", "שליש", "חצי", "חומש"],
    correct: 0,
    explanation: "נשארו 2 מתוך 8 חלקים. 2/8 = 1/4 = רבע!",
    grades: [4], difficulty: "hard",
  },
  {
    id: "frac-29", type: "identify",
    question: "כמה חלקים צריך לצבוע כדי שיהיה שלושה רבעים?",
    visual: { total: 8, filled: 6, shape: "bar" },
    options: ["6 מתוך 8", "4 מתוך 8", "3 מתוך 8", "5 מתוך 8"],
    correct: 0,
    explanation: "שלושה רבעים של 8 זה 6! כי 3/4 = 6/8.",
    grades: [4], difficulty: "hard",
  },
  {
    id: "frac-30", type: "compare",
    question: "מה קטן יותר?",
    visual: {
      left: { total: 6, filled: 2, shape: "bar" },
      right: { total: 4, filled: 2, shape: "bar" },
    },
    options: ["שליש (2/6)", "חצי (2/4)", "שניהם שווים"],
    correct: 0,
    explanation: "2/6 = 1/3 ו-2/4 = 1/2. שליש קטן מחצי!",
    grades: [4], difficulty: "hard",
  },
  {
    id: "frac-31", type: "wordProblem",
    question: "בכוס יש מיץ עד חצי. אם הכוס מחולקת ל-6 סימנים, עד איזה סימן המיץ מגיע?",
    visual: { emoji: "\u{1F9C3}", parts: 6, filled: 3, context: "מיץ" },
    options: ["3", "2", "4", "1"],
    correct: 0,
    explanation: "חצי מ-6 סימנים = 3. המיץ מגיע עד הסימן השלישי!",
    grades: [4], difficulty: "hard",
  },
  {
    id: "frac-32", type: "wordProblem",
    question: "יש 10 סוכריות. נתתי שליש לחבר. כמה סוכריות הוא קיבל? (בקירוב)",
    visual: { emoji: "\u{1F36C}", parts: 3, filled: 1, context: "סוכריות" },
    options: ["3 סוכריות", "5 סוכריות", "2 סוכריות", "4 סוכריות"],
    correct: 0,
    explanation: "שליש מ-10 זה בערך 3. (10 חלקי 3 = 3.33, מעגלים ל-3)",
    grades: [4], difficulty: "hard",
  },
  {
    id: "frac-33", type: "compare",
    question: "מה גדול יותר?",
    visual: {
      left: { total: 5, filled: 4, shape: "circle" },
      right: { total: 3, filled: 2, shape: "circle" },
    },
    options: ["ארבעה חומשים (4/5)", "שני שלישים (2/3)", "שניהם שווים"],
    correct: 0,
    explanation: "4/5 = 0.8 ו-2/3 = 0.66. ארבעה חומשים גדול יותר!",
    grades: [4], difficulty: "hard",
  },
];

export const FRACTION_LEVELS = [
  {
    level: 1,
    nameHe: "חצאים ורבעים",
    filter: { types: ["identify"], difficulties: ["easy"] },
    questionsPerRound: 8,
    grades: [2, 3, 4],
  },
  {
    level: 2,
    nameHe: "שלישים וחמישיות",
    filter: { types: ["identify"], difficulties: ["easy", "medium"] },
    questionsPerRound: 8,
    grades: [2, 3, 4],
  },
  {
    level: 3,
    nameHe: "השוואת שברים",
    filter: { types: ["compare"], difficulties: ["medium"] },
    questionsPerRound: 8,
    grades: [3, 4],
  },
  {
    level: 4,
    nameHe: "שברים בחיי יום-יום",
    filter: { types: ["wordProblem"], difficulties: ["medium"] },
    questionsPerRound: 8,
    grades: [3, 4],
  },
  {
    level: 5,
    nameHe: "אתגר שברים",
    filter: { types: ["identify", "compare", "wordProblem"], difficulties: ["hard"] },
    questionsPerRound: 8,
    grades: [4],
  },
];
