export const QUESTIONS = [
  // =================== TOPIC 1: Analogies ===================
  { id:"1-1",topic:1,grades:[2, 3],difficulty:"easy",
    question:"כלב : נביחה", options:["ברווז : כנפיים","גמל : מים","ציפור : ציוץ","חתול : ליקוק"], correct:2,
    explanation:"הקשר: חיה והקול שהיא משמיעה. כלב נובח, ציפור מצייצת. חתול לא מליקוק (ליקוק זה פעולה לא קול), ברווז וכנפיים זה חיה ואיבר." },
  { id:"1-2",topic:1,grades:[2, 3],difficulty:"easy",
    question:"עין : לראות", options:["אוזן : לשמוע","יד : כפפה","פה : שיניים","רגל : נעל"], correct:0,
    explanation:"הקשר: איבר בגוף והפעולה שלו. עין לראות, אוזן לשמוע." },
  { id:"1-3",topic:1,grades:[2, 3],difficulty:"easy",
    question:"חם : קר", options:["גבוה : נמוך","ירוק : עץ","מהיר : רכב","גדול : בית"], correct:0,
    explanation:"הקשר: מילים הפוכות (ניגודים). חם↔קר, גבוה↔נמוך." },
  { id:"1-4",topic:1,grades:[2],difficulty:"easy",
    question:"לילה : חושך", options:["יום : אור","ערב : ירח","בוקר : ארוחה","צהריים : שמש"], correct:0,
    explanation:"הקשר: זמן ביום והתכונה שלו. לילה=חושך, יום=אור." },
  { id:"1-5",topic:1,grades:[2],difficulty:"easy",
    question:"גשם : מטרייה", options:["שמש : כובע","רוח : עץ","שלג : חורף","עננים : שמיים"], correct:0,
    explanation:"הקשר: תופעת מזג אוויר וחפץ שמגן ממנה. גשם→מטרייה, שמש→כובע." },
  { id:"1-6",topic:1,grades:[2],difficulty:"medium",
    question:"רופא : חולה", options:["מורה : תלמיד","שוטר : ניידת","טייס : מטוס","נהג : כביש"], correct:0,
    explanation:"הקשר: בעל מקצוע והאדם שהוא משרת. רופא מטפל בחולה, מורה מלמד תלמיד." },
  { id:"1-7",topic:1,grades:[2],difficulty:"medium",
    question:"כנף : ציפור", options:["סנפיר : דג","רגל : שולחן","גלגל : מכונית","זנב : חתול"], correct:0,
    explanation:"הקשר: איבר תנועה ייחודי של חיה. כנף=ציפור עפה, סנפיר=דג שוחה." },

  { id:"1-8",topic:1,grades:[2, 3],difficulty:"easy",
    question:"טבח : מטבח", options:["מורה : לימודים","שופט : בית משפט","שליח : משלוח","חולה : בית חולים"], correct:1,
    explanation:"הקשר: בעל מקצוע ומקום עבודתו. טבח→מטבח, שופט→בית משפט." },
  { id:"1-9",topic:1,grades:[3, 4],difficulty:"medium",
    question:"לטרוק : לסגור", options:["לשמוע : להקשיב","להבין : לנחש","לצעוק : לדבר","לתת : להשאיל"], correct:2,
    explanation:"הקשר: פעולה חזקה ופעולה רגילה. לטרוק=לסגור בחוזקה, לצעוק=לדבר בחוזקה." },
  { id:"1-10",topic:1,grades:[2, 3, 4],difficulty:"medium",
    question:"ספר : מדף", options:["כביש : מכונית","מכתב : מעטפה","בגד : ארון","עט : דיו"], correct:2,
    explanation:"הקשר: חפץ ומקום אחסון. ספר במדף, בגד בארון." },
  { id:"1-11",topic:1,grades:[3, 4],difficulty:"medium",
    question:"צמא : שתייה", options:["עייפות : מיטה","רעב : אוכל","קור : מעיל","שמחה : חיוך"], correct:1,
    explanation:"הקשר: צורך ומה שפותר אותו. צמא→שתייה, רעב→אוכל." },
  { id:"1-12",topic:1,grades:[2, 3],difficulty:"medium",
    question:"דבש : מתוק", options:["לימון : חמוץ","מלח : ים","סוכר : עוגה","שוקולד : חום"], correct:0,
    explanation:"הקשר: מאכל והטעם שלו. דבש=מתוק, לימון=חמוץ." },
  { id:"1-13",topic:1,grades:[3, 4],difficulty:"hard",
    question:"אצבע : כפפה", options:["ראש : כובע","עין : משקפיים","רגל : נעל","גוף : חולצה"], correct:2,
    explanation:"הקשר: איבר ולבוש צמוד שמכסה אותו בדיוק. אצבע→כפפה (צמוד), רגל→נעל (צמוד). כובע לא צמוד כמו כפפה." },
  { id:"1-14",topic:1,grades:[3],difficulty:"hard",
    question:"צייר : מכחול", options:["נגר : מסור","שחקן : במה","זמר : שיר","סופר : ספרייה"], correct:0,
    explanation:"הקשר: בעל מקצוע וכלי העבודה שלו. צייר+מכחול, נגר+מסור." },

  { id:"1-15",topic:1,grades:[3, 4],difficulty:"medium",
    question:"זחל : פרפר", options:["ביצה : תרנגולת","ראשן : צפרדע","גור : כלב","זרע : פרח"], correct:1,
    explanation:"הקשר: שלב צעיר ובוגר עם מטמורפוזה (שינוי צורה). זחל→פרפר, ראשן→צפרדע. גור→כלב אין שינוי צורה." },
  { id:"1-16",topic:1,grades:[3, 4],difficulty:"medium",
    question:"שעון : זמן", options:["מד-חום : טמפרטורה","טלפון : שיחה","מפה : דרך","מחשב : חשמל"], correct:0,
    explanation:"הקשר: מכשיר מדידה והדבר שהוא מודד. שעון→זמן, מד-חום→טמפרטורה." },
  { id:"1-17",topic:1,grades:[4],difficulty:"hard",
    question:"מספריים : גזירה", options:["מחט : תפירה","מסרק : שיער","עיפרון : נייר","סיר : מטבח"], correct:0,
    explanation:"הקשר: כלי והפעולה שעושים איתו. מספריים→גזירה, מחט→תפירה." },
  { id:"1-18",topic:1,grades:[4],difficulty:"hard",
    question:"נמלה : שקדנית", options:["שועל : ערמומי","אריה : גדול","דג : מים","ציפור : כנפיים"], correct:0,
    explanation:"הקשר: חיה ותכונת אופי מיוחסת. נמלה=שקדנית, שועל=ערמומי. 'אריה גדול' זו תכונה פיזית לא אופי." },
  { id:"1-19",topic:1,grades:[4],difficulty:"hard",
    question:"מילה : משפט", options:["אות : מילה","פסקה : טקסט","ספרה : מספר","צליל : שיר"], correct:0,
    explanation:"הקשר: יחידה קטנה שמרכיבה יחידה גדולה בדרגה אחת למעלה. מילים→משפט, אותיות→מילה." },
  { id:"1-20",topic:1,grades:[4],difficulty:"medium",
    question:"עלה : עץ", options:["גלגל : אופניים","חלון : בית","כפתור : חולצה","דף : מחברת"], correct:3,
    explanation:"הקשר: חלק אחד מתוך הרבה חלקים זהים בשלם. עלים רבים על עץ, דפים רבים במחברת." },

  // =================== TOPIC 2: Missing Words ===================
  { id:"2-1",topic:2,grades:[2, 3],difficulty:"easy",
    question:'הילד רץ ______ כי הוא ______ לאוטובוס.',
    options:["לאט / חיכה","מהר / איחר","הביתה / חזר","שמח / אהב"], correct:1,
    explanation:'מהר/איחר - יש קשר סיבתי: הוא רץ מהר בגלל שאיחר.' },
  { id:"2-2",topic:2,grades:[2, 3],difficulty:"easy",
    question:'הכלב ______ כאשר הוא ______ אדם זר.',
    options:["ישן / ראה","נבח / שמע","שתק / פגש","אכל / הריח"], correct:1,
    explanation:'כלבים נובחים כששומעים אדם זר - תגובה טבעית.' },
  { id:"2-3",topic:2,grades:[2],difficulty:"easy",
    question:'אמא ביקשה ממני ______ את החדר כי הוא היה ______.',
    options:["לנקות / מלוכלך","לצבוע / גדול","לפתוח / סגור","לסגור / פתוח"], correct:0,
    explanation:'ביקשה לנקות כי מלוכלך - קשר סיבתי ברור.' },
  { id:"2-4",topic:2,grades:[2],difficulty:"easy",
    question:'בחורף אני אוהב לשתות ______ כי בחוץ ______.',
    options:["שוקו חם / קר","מים / חם","מיץ / יפה","תה / בוקר"], correct:0,
    explanation:'בחורף קר, לכן שותים שוקו חם.' },
  { id:"2-5",topic:2,grades:[2],difficulty:"medium",
    question:'הציפור בנתה ______ על ______ הגבוה של העץ.',
    options:["קן / הענף","בית / הגזע","גשר / השורש","חור / העלה"], correct:0,
    explanation:'ציפורים בונות קן על ענפים גבוהים.' },
  { id:"2-6",topic:2,grades:[2],difficulty:"medium",
    question:'אני ______ בבוקר ו______ בלילה.',
    options:["קם / ישן","ישן / קם","אוכל / שותה","שמח / עצוב"], correct:0,
    explanation:'סדר יום: בבוקר קמים, בלילה ישנים.' },

  { id:"2-7",topic:2,grades:[2, 3],difficulty:"medium",
    question:'תמר לומדת לנגן ______ בפסנתר ______ בגיטרה.',
    options:["רק / וגם","גם / ורק","גם / וגם","רק / ורק"], correct:2,
    explanation:'"גם / וגם" - היחידה שהגיונית. אם מנגנת בשניהם, הגיוני לומר "גם בפסנתר וגם בגיטרה".' },
  { id:"2-8",topic:2,grades:[3, 4],difficulty:"medium",
    question:'זכרתי בעל-פה את כל ______ אף על פי ש______.',
    options:["המילים של השיר / שמעתי אותו רק פעם אחת","רשימת המכולת / היא כללה רק לחם","שמות המקומות / לא הייתי בהם","מערכת השעות / היא לא השתנתה"], correct:0,
    explanation:'"אף על פי ש" = ניגוד. מפתיע שזכרתי למרות שרק שמעתי פעם אחת.' },
  { id:"2-9",topic:2,grades:[3, 4],difficulty:"hard",
    question:'הספר הזה כל כך ______ שלא יכולתי ______ לקרוא אותו.',
    options:["מעניין / להפסיק","ארוך / לסיים","כבד / להרים","יקר / לקנות"], correct:0,
    explanation:'ספר מעניין → לא יכולתי להפסיק לקרוא. ביטוי נפוץ.' },
  { id:"2-10",topic:2,grades:[3, 4],difficulty:"hard",
    question:'______ שירד גשם, הילדים ______ בחוץ כאילו שום דבר לא ______.',
    options:["למרות / שיחקו / קרה","כי / ישבו / השתנה","בגלל / נשארו / עזר","אחרי / רקדו / נגמר"], correct:0,
    explanation:'"למרות" = ניגוד. למרות הגשם, שיחקו כאילו כלום לא קרה.' },
  { id:"2-11",topic:2,grades:[3],difficulty:"medium",
    question:'ככל שהתרגלתי ______, כך נהיה לי ______ יותר.',
    options:["יותר / קל","פחות / קשה","מהר / משעמם","שוב / עצוב"], correct:0,
    explanation:'"ככל ש...כך" = קשר ישיר. תרגול→קל יותר.' },

  { id:"2-12",topic:2,grades:[4],difficulty:"medium",
    question:'מתן קנה בחנות ______ שמלא ב______ שהוא אוהב ______.',
    options:["זר / פרחים / מים","קופסה / צבעים / לצייר","חבילה / דפים / לקרוא","אסף / קלפים / לשיר"], correct:1,
    explanation:'קנה קופסה מלאה בצבעים שהוא אוהב לצייר - הגיוני ושלם.' },
  { id:"2-13",topic:2,grades:[4],difficulty:"hard",
    question:'יעל אמרה: "______ כי מחר יש לי מבחן ______."',
    options:["היום למדתי / שהיה לי השבוע","מחר אלמד / שיש לי עכשיו","שלשום למדתי / שאתמול היה לי","אני לומדת / שהיה לי שלשום"], correct:2,
    explanation:'סדר זמנים: שלשום למדתי, אתמול היה מבחן, מחר יש עוד. התאמת זמנים.' },
  { id:"2-14",topic:2,grades:[4],difficulty:"hard",
    question:'______ שהמשחק יתחיל, הקהל כבר ______ את המקומות.',
    options:["לפני / מילא","אחרי / פינה","בזמן / חיפש","למרות / שמר"], correct:0,
    explanation:'לפני שהמשחק התחיל, הקהל כבר מילא את המקומות.' },
  { id:"2-15",topic:2,grades:[4],difficulty:"hard",
    question:'דווקא כשחשבתי ש______, גיליתי ש______.',
    options:["הכל אבוד / יש עוד סיכוי","הצלחתי / עשיתי טוב","זה קל / אני יכול","אין בעיה / הכל בסדר"], correct:0,
    explanation:'"דווקא" = הפתעה וניגוד. חשבתי שאבוד → גיליתי שיש סיכוי.' },

  // =================== TOPIC 3: Word Problems ===================
  { id:"3-1",topic:3,grades:[2],difficulty:"easy",
    question:"לדנה יש 24 סוכריות. היא רוצה לחלק שווה בשווה בין 4 חברות. כמה סוכריות תקבל כל חברה?",
    options:["4","6","8","20"], correct:1,
    explanation:"24 ÷ 4 = 6 סוכריות לכל חברה." },
  { id:"3-2",topic:3,grades:[2],difficulty:"easy",
    question:"לתומר יש 15 גולות. הוא נתן 4 ליוסי וקיבל 7 מרוני. כמה גולות יש לו עכשיו?",
    options:["8","12","18","26"], correct:2,
    explanation:"15 - 4 + 7 = 18 גולות." },
  { id:"3-3",topic:3,grades:[2, 3],difficulty:"medium",
    question:"ברכבת 8 קרונות, בכל קרון 30 מקומות. כמה אנשים יכולים לשבת?",
    options:["38","80","240","300"], correct:2,
    explanation:"8 × 30 = 240 מקומות." },
  { id:"3-4",topic:3,grades:[2, 3],difficulty:"medium",
    question:"בחניון 5 שורות של מכוניות, בכל שורה 8. נסעו 7 מכוניות. כמה נשארו?",
    options:["28","33","35","40"], correct:1,
    explanation:"5 × 8 = 40. 40 - 7 = 33." },
  { id:"3-5",topic:3,grades:[2, 3],difficulty:"medium",
    question:"בגן חיות 4 פילים, 6 נמרים ו-10 ציפורים. כמה רגליים יש לכולם?",
    options:["40","60","80","100"], correct:1,
    explanation:"פילים: 4×4=16, נמרים: 6×4=24, ציפורים: 10×2=20. סה\"כ: 60." },

  { id:"3-6",topic:3,grades:[2, 3],difficulty:"medium",
    question:"כל משפחת לוי הלכה לגלידרייה. לכל אחד 2 כדורים. סה\"כ 14 כדורים. כמה בני משפחה?",
    options:["6","7","12","16"], correct:1,
    explanation:"14 ÷ 2 = 7 בני משפחה." },
  { id:"3-7",topic:3,grades:[3, 4],difficulty:"medium",
    question:"אורי קנה 3 מחברות ב-12 ₪ כל אחת ו-2 עטים ב-5 ₪. שילם 100 ₪. כמה עודף?",
    options:["46","54","64","83"], correct:1,
    explanation:"3×12=36, 2×5=10. סה\"כ 46. עודף: 100-46=54." },
  { id:"3-8",topic:3,grades:[3, 4],difficulty:"hard",
    question:"שעון מראה 3:45. כמה דקות עברו מ-2:20?",
    options:["65","75","85","125"], correct:2,
    explanation:"מ-2:20 עד 3:20 = 60 דקות. עוד 25 = 85 דקות." },
  { id:"3-9",topic:3,grades:[3, 4],difficulty:"hard",
    question:"חנות מוכרת תפוחים בשקיות של 6. אמא צריכה 50. כמה שקיות לפחות?",
    options:["7","8","9","10"], correct:2,
    explanation:"50÷6=8 שארית 2. 8 שקיות=48 לא מספיק. צריך 9 שקיות=54." },

  { id:"3-10",topic:3,grades:[4],difficulty:"medium",
    question:"באולם 17 שורות, בכל שורה 11 כסאות. כמה כסאות יש?",
    options:["28","107","170","187"], correct:3,
    explanation:"17×11 = 17×10+17 = 170+17 = 187." },
  { id:"3-11",topic:3,grades:[4],difficulty:"hard",
    question:"בכיתה 28 תלמידים. הבנות פי 3 מהבנים. כמה בנים?",
    options:["4","7","9","14"], correct:1,
    explanation:"בנים=x, בנות=3x. x+3x=28, 4x=28, x=7." },
  { id:"3-12",topic:3,grades:[4],difficulty:"hard",
    question:"מספר אי-זוגי דו-ספרתי, סכום ספרותיו 11, ספרת עשרות גדולה ב-3 מאחדות. מהו?",
    options:["11","36","47","83"], correct:2,
    explanation:"אם אחדות=x, עשרות=x+3. x+(x+3)=11, x=4. המספר: 74. אבל 74 זוגי! הפוך: 47. 4+7=11, 7-4=3, 47 אי-זוגי ✓" },
  { id:"3-13",topic:3,grades:[4],difficulty:"hard",
    question:"בניין 5 קומות. בראשונה 2 דירות, בכל קומה דירה נוספת. כמה דירות?",
    options:["10","15","20","25"], correct:2,
    explanation:"קומה 1:2, 2:3, 3:4, 4:5, 5:6. סה\"כ 2+3+4+5+6=20." },
  { id:"3-14",topic:3,grades:[4],difficulty:"hard",
    question:"מיכל גדולה מנועה ב-3. נועה גדולה מעידו ב-2. מיכל בת 10. סכום גילאיהם?",
    options:["22","24","25","27"], correct:0,
    explanation:"מיכל=10, נועה=7, עידו=5. סה\"כ 10+7+5=22." },

  // =================== TOPIC 4: Missing Number ===================
  { id:"4-1",topic:4,grades:[2, 3],difficulty:"easy",
    question:"circles_sum",
    visual:{type:"circles_trio",circles:[{top:[5,4],bottom:9},{top:[8,3],bottom:11},{top:[7,6],bottom:"?"}]},
    options:["9","10","13","42"], correct:2,
    explanation:"הכלל: למטה = סכום למעלה. 5+4=9, 8+3=11, 7+6=13." },
  { id:"4-2",topic:4,grades:[2],difficulty:"easy",
    question:"circles_plus1",
    visual:{type:"circles_trio",circles:[{top:[3,4],bottom:8},{top:[6,2],bottom:9},{top:[5,5],bottom:"?"}]},
    options:["10","11","12","15"], correct:1,
    explanation:"הכלל: למטה = סכום +1. 3+4+1=8, 6+2+1=9, 5+5+1=11." },
  { id:"4-3",topic:4,grades:[2, 3],difficulty:"medium",
    question:"circles_mult",
    visual:{type:"circles_trio",circles:[{top:[3,2],bottom:6},{top:[4,3],bottom:12},{top:[5,4],bottom:"?"}]},
    options:["9","15","20","24"], correct:2,
    explanation:"הכלל: למטה = מכפלת למעלה. 3×2=6, 4×3=12, 5×4=20." },
  { id:"4-4",topic:4,grades:[2, 3],difficulty:"medium",
    question:"circles_mult2",
    visual:{type:"circles_trio",circles:[{top:[2,5],bottom:10},{top:[3,4],bottom:12},{top:[6,3],bottom:"?"}]},
    options:["9","12","18","21"], correct:2,
    explanation:"הכלל: למטה = מכפלת למעלה. 2×5=10, 3×4=12, 6×3=18." },
  { id:"4-5",topic:4,grades:[2],difficulty:"medium",
    question:"seq_add2",
    visual:{type:"sequence",numbers:[1,3,5,7,"?"]},
    options:["8","9","10","11"], correct:1,
    explanation:"סדרה: +2 בכל פעם. 1,3,5,7,9." },
  { id:"4-6",topic:4,grades:[2],difficulty:"hard",
    question:"circles_div",
    visual:{type:"circles_trio",circles:[{top:[12,3],bottom:4},{top:[20,4],bottom:5},{top:[18,6],bottom:"?"}]},
    options:["2","3","12","24"], correct:1,
    explanation:"הכלל: למטה = חלוקה. 12÷3=4, 20÷4=5, 18÷6=3." },

  { id:"4-7",topic:4,grades:[3, 4],difficulty:"medium",
    question:"circles_product",
    visual:{type:"circles_trio",circles:[{top:[10,2],bottom:20},{top:[9,3],bottom:27},{top:[8,"?"],bottom:32}]},
    options:["4","6","12","24"], correct:0,
    explanation:"הכלל: למטה = מכפלה. 10×2=20, 9×3=27, 8×?=32, ?=4." },
  { id:"4-8",topic:4,grades:[3, 4],difficulty:"medium",
    question:"seq_mult2",
    visual:{type:"sequence",numbers:[2,4,8,16,"?"]},
    options:["18","24","32","64"], correct:2,
    explanation:"סדרה: ×2 בכל פעם. 2,4,8,16,32." },
  { id:"4-9",topic:4,grades:[3],difficulty:"medium",
    question:"triangle1",
    visual:{type:"triangle_pyramid",numbers:{top:"?",midLeft:4,midRight:9,botLeft:7,botMid:11,botRight:20}},
    options:["5","13","14","29"], correct:1,
    explanation:"הכלל: כל מספר = סכום שניים מתחתיו. 4+9=13. ?=13." },
  { id:"4-10",topic:4,grades:[3],difficulty:"hard",
    question:"seq_growing",
    visual:{type:"sequence",numbers:[1,2,4,7,11,"?"]},
    options:["14","15","16","22"], correct:2,
    explanation:"הפרשים גדלים: +1,+2,+3,+4,+5. 11+5=16." },
  { id:"4-11",topic:4,grades:[3],difficulty:"hard",
    question:"circles_diff",
    visual:{type:"circles_trio",circles:[{top:[15,6],bottom:9},{top:[20,8],bottom:12},{top:[18,5],bottom:"?"}]},
    options:["10","13","23","90"], correct:1,
    explanation:"הכלל: למטה = הפרש. 15-6=9, 20-8=12, 18-5=13." },

  { id:"4-12",topic:4,grades:[4],difficulty:"medium",
    question:"sq_arrows",
    visual:{type:"squares_arrows",rows:[{left:16,center:2,right:8},{left:"?",center:4,right:10}]},
    options:["14","20","40","80"], correct:2,
    explanation:"הכלל: שמאל = אמצע × ימין. 2×8=16, 4×10=40." },
  { id:"4-13",topic:4,grades:[4],difficulty:"hard",
    question:"circles_prodplus",
    visual:{type:"circles_trio",circles:[{top:[3,2],bottom:8},{top:[4,3],bottom:14},{top:[5,2],bottom:"?"}]},
    options:["10","12","14","22"], correct:1,
    explanation:"הכלל: למטה = מכפלה +2. 3×2+2=8, 4×3+2=14, 5×2+2=12." },
  { id:"4-14",topic:4,grades:[4],difficulty:"hard",
    question:"circles_avg",
    visual:{type:"circles_trio",circles:[{top:[6,4],bottom:5},{top:[10,8],bottom:9},{top:[14,2],bottom:"?"}]},
    options:["6","8","12","16"], correct:1,
    explanation:"הכלל: למטה = ממוצע. (6+4)/2=5, (10+8)/2=9, (14+2)/2=8." },
  { id:"4-15",topic:4,grades:[4],difficulty:"hard",
    question:"seq_down",
    visual:{type:"sequence",numbers:[81,27,9,3,"?"]},
    options:["0","1","2","3"], correct:1,
    explanation:"סדרה: ÷3 בכל פעם. 81,27,9,3,1." },
  { id:"4-16",topic:4,grades:[4],difficulty:"hard",
    question:"sq_complex",
    visual:{type:"squares_arrows",rows:[{left:5,center:3,right:8},{left:7,center:"?",right:12}]},
    options:["3","5","7","19"], correct:1,
    explanation:"הכלל: ימין = שמאל + אמצע. 5+3=8, 7+?=12, ?=5." },

  // =================== TOPIC 5: Next Shape (ALL VISUAL) ===================
  // --- GRADE 2: simpler patterns ---
  { id:"5-1",topic:5,grades:[2, 3],difficulty:"easy",
    question:"shape_sides_inc",
    visual:{
      type:"shape_row",
      sequence:[
        {shape:"triangle",stroke:"#22d3ee"},{shape:"square",stroke:"#22d3ee"},{shape:"pentagon",stroke:"#22d3ee"}
      ]
    },
    options:[
      {shape:"hexagon",stroke:"#22d3ee"},
      {shape:"circle",stroke:"#22d3ee"},
      {shape:"triangle",stroke:"#22d3ee"},
      {shape:"octagon",stroke:"#22d3ee"}
    ],
    correct:0,
    explanation:"הכלל: מספר הצלעות עולה ב-1. משולש(3)→ריבוע(4)→מחומש(5)→משושה(6)." },

  { id:"5-2",topic:5,grades:[2, 3],difficulty:"easy",
    question:"alternating_shapes",
    visual:{
      type:"shape_row",
      sequence:[
        {shape:"circle",stroke:"#f87171"},{shape:"square",stroke:"#f87171"},{shape:"circle",stroke:"#f87171"},{shape:"square",stroke:"#f87171"}
      ]
    },
    options:[
      {shape:"circle",stroke:"#f87171"},
      {shape:"square",stroke:"#f87171"},
      {shape:"triangle",stroke:"#f87171"},
      {shape:"diamond",stroke:"#f87171"}
    ],
    correct:0,
    explanation:"הכלל: הצורות מתחלפות - עיגול, ריבוע, עיגול, ריבוע, עיגול." },

  { id:"5-3",topic:5,grades:[2, 3],difficulty:"medium",
    question:"growing_fill",
    visual:{
      type:"shape_row",
      sequence:[
        {shape:"circle",stroke:"#4ade80",fill:"none"},
        {shape:"circle",stroke:"#4ade80",fill:"rgba(74,222,128,0.3)"},
        {shape:"circle",stroke:"#4ade80",fill:"rgba(74,222,128,0.6)"}
      ]
    },
    options:[
      {shape:"circle",stroke:"#4ade80",fill:"none"},
      {shape:"circle",stroke:"#4ade80",fill:"#4ade80"},
      {shape:"circle",stroke:"#4ade80",fill:"rgba(74,222,128,0.3)"},
      {shape:"square",stroke:"#4ade80",fill:"#4ade80"}
    ],
    correct:1,
    explanation:"הכלל: העיגול מתמלא בהדרגה - ריק→שליש→שני שליש→מלא." },

  { id:"5-4",topic:5,grades:[2, 3],difficulty:"medium",
    question:"rotation_arrow",
    visual:{
      type:"shape_row",
      sequence:[
        {shape:"arrow_up",stroke:"#818cf8",rotation:0},
        {shape:"arrow_up",stroke:"#818cf8",rotation:90},
        {shape:"arrow_up",stroke:"#818cf8",rotation:180},
        {shape:"arrow_up",stroke:"#818cf8",rotation:270}
      ]
    },
    options:[
      {shape:"arrow_up",stroke:"#818cf8",rotation:0},
      {shape:"arrow_up",stroke:"#818cf8",rotation:45},
      {shape:"arrow_up",stroke:"#818cf8",rotation:180},
      {shape:"arrow_up",stroke:"#818cf8",rotation:270}
    ],
    correct:0,
    explanation:"הכלל: החץ מסתובב 90° בכיוון השעון. ↑→→↓→←→↑ (חוזר)." },

  { id:"5-5",topic:5,grades:[2],difficulty:"hard",
    question:"color_alt_shape",
    visual:{
      type:"shape_row",
      sequence:[
        {shape:"circle",stroke:"#f87171",fill:"#f87171"},
        {shape:"circle",stroke:"#60a5fa",fill:"none"},
        {shape:"circle",stroke:"#f87171",fill:"#f87171"},
        {shape:"circle",stroke:"#60a5fa",fill:"none"}
      ]
    },
    options:[
      {shape:"circle",stroke:"#f87171",fill:"#f87171"},
      {shape:"circle",stroke:"#60a5fa",fill:"none"},
      {shape:"circle",stroke:"#f87171",fill:"none"},
      {shape:"square",stroke:"#f87171",fill:"#f87171"}
    ],
    correct:0,
    explanation:"הכלל: עיגול אדום מלא, עיגול כחול ריק, חוזר. הבא: אדום מלא." },

  // --- GRADE 3: more complex patterns ---
  { id:"5-6",topic:5,grades:[3, 4],difficulty:"medium",
    question:"shape_color_double",
    visual:{
      type:"shape_row",
      sequence:[
        {shape:"triangle",stroke:"#f87171"},{shape:"square",stroke:"#60a5fa"},{shape:"pentagon",stroke:"#4ade80"},{shape:"hexagon",stroke:"#f87171"}
      ]
    },
    options:[
      {shape:"heptagon",stroke:"#60a5fa"},
      {shape:"heptagon",stroke:"#4ade80"},
      {shape:"hexagon",stroke:"#60a5fa"},
      {shape:"octagon",stroke:"#f87171"}
    ],
    correct:0,
    explanation:"שני כללים: 1) צלעות עולות: 3,4,5,6,7. 2) צבע מתחלף: אדום,כחול,ירוק,אדום,כחול. הבא: 7 צלעות + כחול." },

  { id:"5-7",topic:5,grades:[3, 4],difficulty:"medium",
    question:"inner_shape_change",
    visual:{
      type:"shape_row",
      sequence:[
        {shape:"square",stroke:"#818cf8",inner:"circle",innerColor:"#fbbf24"},
        {shape:"square",stroke:"#818cf8",inner:"square",innerColor:"#fbbf24"},
        {shape:"square",stroke:"#818cf8",inner:"triangle",innerColor:"#fbbf24"}
      ]
    },
    options:[
      {shape:"square",stroke:"#818cf8",inner:"circle",innerColor:"#fbbf24"},
      {shape:"circle",stroke:"#818cf8",inner:"square",innerColor:"#fbbf24"},
      {shape:"square",stroke:"#818cf8",inner:"dot",innerColor:"#fbbf24"},
      {shape:"triangle",stroke:"#818cf8",inner:"circle",innerColor:"#fbbf24"}
    ],
    correct:0,
    explanation:"הכלל: הצורה החיצונית נשארת ריבוע, הפנימית מתחלפת: עיגול→ריבוע→משולש→עיגול (חוזר)." },

  { id:"5-8",topic:5,grades:[3, 4],difficulty:"hard",
    question:"matrix_color_shape",
    visual:{
      type:"matrix_3x3",
      grid:[
        [{shape:"circle",stroke:"#f87171",fill:"#f87171"},{shape:"circle",stroke:"#60a5fa",fill:"#60a5fa"},{shape:"circle",stroke:"#4ade80",fill:"#4ade80"}],
        [{shape:"square",stroke:"#f87171",fill:"#f87171"},{shape:"square",stroke:"#60a5fa",fill:"#60a5fa"},{shape:"square",stroke:"#4ade80",fill:"#4ade80"}],
        [{shape:"triangle",stroke:"#f87171",fill:"#f87171"},{shape:"triangle",stroke:"#60a5fa",fill:"#60a5fa"},null]
      ]
    },
    options:[
      {shape:"triangle",stroke:"#4ade80",fill:"#4ade80"},
      {shape:"triangle",stroke:"#f87171",fill:"#f87171"},
      {shape:"square",stroke:"#4ade80",fill:"#4ade80"},
      {shape:"circle",stroke:"#4ade80",fill:"#4ade80"}
    ],
    correct:0,
    explanation:"שורות: אותה צורה, צבעים אדום-כחול-ירוק. עמודות: אותו צבע, צורות עיגול-ריבוע-משולש. חסר: משולש ירוק." },

  { id:"5-9",topic:5,grades:[3, 4],difficulty:"hard",
    question:"rotation_with_size",
    visual:{
      type:"shape_row",
      sequence:[
        {shape:"triangle",stroke:"#22d3ee",rotation:0,strokeWidth:2},
        {shape:"triangle",stroke:"#22d3ee",rotation:90,strokeWidth:2},
        {shape:"triangle",stroke:"#22d3ee",rotation:180,strokeWidth:2}
      ]
    },
    options:[
      {shape:"triangle",stroke:"#22d3ee",rotation:270},
      {shape:"triangle",stroke:"#22d3ee",rotation:0},
      {shape:"square",stroke:"#22d3ee",rotation:270},
      {shape:"triangle",stroke:"#22d3ee",rotation:180}
    ],
    correct:0,
    explanation:"הכלל: המשולש מסתובב 90° בכל פעם. 0°→90°→180°→270°." },

  { id:"5-10",topic:5,grades:[3],difficulty:"hard",
    question:"dot_position",
    visual:{
      type:"shape_row",
      sequence:[
        {shape:"circle",stroke:"#818cf8",dot:"top",dotColor:"#fbbf24"},
        {shape:"circle",stroke:"#818cf8",dot:"right",dotColor:"#fbbf24"},
        {shape:"circle",stroke:"#818cf8",dot:"bottom",dotColor:"#fbbf24"}
      ]
    },
    options:[
      {shape:"circle",stroke:"#818cf8",dot:"left",dotColor:"#fbbf24"},
      {shape:"circle",stroke:"#818cf8",dot:"top",dotColor:"#fbbf24"},
      {shape:"circle",stroke:"#818cf8",dot:"center",dotColor:"#fbbf24"},
      {shape:"square",stroke:"#818cf8",dot:"left",dotColor:"#fbbf24"}
    ],
    correct:0,
    explanation:"הכלל: הנקודה הצהובה זזה בכיוון השעון: למעלה→ימין→למטה→שמאל." },

  // --- GRADE 4: complex matrices ---
  { id:"5-11",topic:5,grades:[4],difficulty:"medium",
    question:"matrix_rotation_fill",
    visual:{
      type:"matrix_3x3",
      grid:[
        [{shape:"triangle",stroke:"#f87171",rotation:0},{shape:"triangle",stroke:"#f87171",rotation:90},{shape:"triangle",stroke:"#f87171",rotation:180}],
        [{shape:"square",stroke:"#60a5fa",rotation:0},{shape:"square",stroke:"#60a5fa",rotation:90},{shape:"square",stroke:"#60a5fa",rotation:180}],
        [{shape:"diamond",stroke:"#4ade80",rotation:0},{shape:"diamond",stroke:"#4ade80",rotation:90},null]
      ]
    },
    options:[
      {shape:"diamond",stroke:"#4ade80",rotation:180},
      {shape:"diamond",stroke:"#4ade80",rotation:270},
      {shape:"triangle",stroke:"#4ade80",rotation:180},
      {shape:"square",stroke:"#4ade80",rotation:180}
    ],
    correct:0,
    explanation:"שורות: אותה צורה+צבע, סיבוב 0°→90°→180°. עמודות: אותו סיבוב, צורה משתנה. חסר: מעוין ירוק 180°." },

  { id:"5-12",topic:5,grades:[4],difficulty:"hard",
    question:"matrix_inner_outer",
    visual:{
      type:"matrix_3x3",
      grid:[
        [{shape:"square",stroke:"#f87171",inner:"circle",innerColor:"#f87171"},{shape:"square",stroke:"#60a5fa",inner:"circle",innerColor:"#60a5fa"},{shape:"square",stroke:"#4ade80",inner:"circle",innerColor:"#4ade80"}],
        [{shape:"circle",stroke:"#f87171",inner:"square",innerColor:"#f87171"},{shape:"circle",stroke:"#60a5fa",inner:"square",innerColor:"#60a5fa"},{shape:"circle",stroke:"#4ade80",inner:"square",innerColor:"#4ade80"}],
        [{shape:"triangle",stroke:"#f87171",inner:"dot",innerColor:"#f87171"},{shape:"triangle",stroke:"#60a5fa",inner:"dot",innerColor:"#60a5fa"},null]
      ]
    },
    options:[
      {shape:"triangle",stroke:"#4ade80",inner:"dot",innerColor:"#4ade80"},
      {shape:"triangle",stroke:"#f87171",inner:"dot",innerColor:"#f87171"},
      {shape:"circle",stroke:"#4ade80",inner:"dot",innerColor:"#4ade80"},
      {shape:"square",stroke:"#4ade80",inner:"circle",innerColor:"#4ade80"}
    ],
    correct:0,
    explanation:"שורות: אותה צורה חיצונית+פנימית, צבע משתנה (אדום,כחול,ירוק). עמודות: אותו צבע, צורה חיצונית משתנה. חסר: משולש ירוק עם נקודה." },

  { id:"5-13",topic:5,grades:[4],difficulty:"hard",
    question:"triple_rule",
    visual:{
      type:"shape_row",
      sequence:[
        {shape:"circle",stroke:"#f87171",fill:"none"},
        {shape:"square",stroke:"#60a5fa",fill:"#60a5fa"},
        {shape:"triangle",stroke:"#4ade80",fill:"none"},
        {shape:"diamond",stroke:"#fbbf24",fill:"#fbbf24"},
        {shape:"pentagon",stroke:"#f87171",fill:"none"}
      ]
    },
    options:[
      {shape:"hexagon",stroke:"#60a5fa",fill:"#60a5fa"},
      {shape:"hexagon",stroke:"#60a5fa",fill:"none"},
      {shape:"pentagon",stroke:"#60a5fa",fill:"#60a5fa"},
      {shape:"hexagon",stroke:"#4ade80",fill:"#4ade80"}
    ],
    correct:0,
    explanation:"3 כללים: 1) צלעות עולות. 2) צבע מתחלף: אדום,כחול,ירוק,צהוב,אדום,כחול. 3) מילוי מתחלף: ריק,מלא,ריק,מלא. הבא: משושה(6) + כחול + מלא." },

  { id:"5-14",topic:5,grades:[4],difficulty:"hard",
    question:"matrix_3rules",
    visual:{
      type:"matrix_3x3",
      grid:[
        [{shape:"circle",stroke:"#f87171",fill:"none",inner:"dot",innerColor:"#f87171"},{shape:"circle",stroke:"#60a5fa",fill:"#60a5fa"},{shape:"circle",stroke:"#4ade80",fill:"none",inner:"dot",innerColor:"#4ade80"}],
        [{shape:"square",stroke:"#60a5fa",fill:"#60a5fa"},{shape:"square",stroke:"#4ade80",fill:"none",inner:"dot",innerColor:"#4ade80"},{shape:"square",stroke:"#f87171",fill:"#f87171"}],
        [{shape:"triangle",stroke:"#4ade80",fill:"none",inner:"dot",innerColor:"#4ade80"},{shape:"triangle",stroke:"#f87171",fill:"#f87171"},null]
      ]
    },
    options:[
      {shape:"triangle",stroke:"#60a5fa",fill:"#60a5fa"},
      {shape:"triangle",stroke:"#60a5fa",fill:"none",inner:"dot",innerColor:"#60a5fa"},
      {shape:"circle",stroke:"#60a5fa",fill:"#60a5fa"},
      {shape:"triangle",stroke:"#4ade80",fill:"#4ade80"}
    ],
    correct:0,
    explanation:"בכל שורה: אותה צורה, 3 צבעים שונים, ו-3 סגנונות (נקודה, מלא, נקודה). בעמודה: צבעים מזיזים. חסר: משולש כחול מלא." },

  { id:"5-15",topic:5,grades:[4],difficulty:"hard",
    question:"complex_sequence",
    visual:{type:"shape_row",sequence:[
        {shape:"triangle",stroke:"#22d3ee",fill:"none",rotation:0},
        {shape:"triangle",stroke:"#22d3ee",fill:"none",rotation:180},
        {shape:"square",stroke:"#22d3ee",fill:"#22d3ee",rotation:0},
        {shape:"square",stroke:"#22d3ee",fill:"#22d3ee",rotation:45},
        {shape:"pentagon",stroke:"#22d3ee",fill:"none",rotation:0}
    ]},
    options:[
      {shape:"pentagon",stroke:"#22d3ee",fill:"none",rotation:180},
      {shape:"pentagon",stroke:"#22d3ee",fill:"#22d3ee",rotation:0},
      {shape:"hexagon",stroke:"#22d3ee",fill:"none",rotation:0},
      {shape:"pentagon",stroke:"#22d3ee",fill:"#22d3ee",rotation:180}
    ],
    correct:0,
    explanation:"כללים: 1) כל צורה מופיעה פעמיים. 2) במופע השני יש סיבוב. 3) מילוי מתחלף בין זוגות. הבא: מחומש מסובב." },

  // ===== EXTRA QUESTIONS: TOPIC 1 =====
  { id:"1-50",topic:1,grades:[2, 3],difficulty:"medium",
    question:"חלב : גבינה", options:["ענבים : יין","מים : ברז","לחם : חיטה","ביצה : תרנגולת"], correct:0,
    explanation:"הקשר: חומר גלם והמוצר שמכינים ממנו. מחלב→גבינה, מענבים→יין." },
  { id:"1-51",topic:1,grades:[2, 3],difficulty:"medium",
    question:"מלך : כתר", options:["שוטר : אקדח","ליצן : אף אדום","רופא : מזרק","חייל : מדים"], correct:1,
    explanation:"הקשר: דמות והסמל המזהה שלה. מלך=כתר, ליצן=אף אדום." },
  { id:"1-52",topic:1,grades:[2],difficulty:"hard",
    question:"סולם : מדרגות", options:["אופניים : מכונית","עיפרון : מחשב","ספינה : מטוס","נר : מנורה"], correct:3,
    explanation:"דבר פשוט/ישן ודבר מתקדם עם אותה מטרה. סולם ומדרגות=לטפס. נר ומנורה=תאורה." },
  { id:"1-53",topic:1,grades:[2],difficulty:"hard",
    question:"חורף : קר", options:["קיץ : חם","סתיו : גשם","אביב : פרחים","לילה : ירח"], correct:0,
    explanation:"עונה ותכונה מרכזית. חורף=קר, קיץ=חם." },
  { id:"1-54",topic:1,grades:[3, 4],difficulty:"hard",
    question:"עכביש : רשת", options:["דבורה : דבש","ציפור : קן","תולעת : אדמה","נמלה : גבעה"], correct:0,
    explanation:"חיה ומוצר שהיא מייצרת מגופה. עכביש→רשת, דבורה→דבש." },
  { id:"1-55",topic:1,grades:[3, 4],difficulty:"hard",
    question:"מפתח : מנעול", options:["שלט : טלוויזיה","כפתור : חולצה","פקק : בקבוק","חגורה : מכנסיים"], correct:0,
    explanation:"כלי שמפעיל/פותח משהו ספציפי. מפתח→מנעול, שלט→טלוויזיה." },
  { id:"1-56",topic:1,grades:[3],difficulty:"hard",
    question:"אי : ים", options:["הר : שלג","ירח : שמיים","אגם : יער","ענן : רוח"], correct:1,
    explanation:"גוף מוקף/נמצא בתוך דבר גדול. אי בים, ירח בשמיים." },
  { id:"1-57",topic:1,grades:[4],difficulty:"hard",
    question:"בצורת : רעב", options:["שיטפון : הרס","מגפה : מוות","רעידת אדמה : פחד","סערה : רוח"], correct:0,
    explanation:"אסון טבע ותוצאה ישירה. בצורת→רעב, שיטפון→הרס." },
  { id:"1-58",topic:1,grades:[4],difficulty:"hard",
    question:"מיקרוסקופ : חיידק", options:["טלסקופ : כוכב","משקפיים : ספר","זכוכית מגדלת : עיתון","מראה : פנים"], correct:0,
    explanation:"מכשיר אופטי ודבר שרואים רק דרכו. מיקרוסקופ→חיידק, טלסקופ→כוכב." },
  { id:"1-59",topic:1,grades:[4],difficulty:"hard",
    question:"סימפוניה : מנצח", options:["סרט : במאי","שיר : זמר","ספר : קורא","תמונה : מוזיאון"], correct:0,
    explanation:"יצירה והאדם שמוביל ביצועה. סימפוניה→מנצח, סרט→במאי." },

  // ===== EXTRA QUESTIONS: TOPIC 2 =====
  { id:"2-50",topic:2,grades:[2, 3],difficulty:"medium",
    question:'השמש ______ והילדים ______ לשחק בחוץ.',
    options:["זרחה / יצאו","שקעה / רצו","נעלמה / אהבו","עלתה / פחדו"], correct:0,
    explanation:'שמש זורחת → ילדים יוצאים. קשר סיבתי.' },
  { id:"2-51",topic:2,grades:[2],difficulty:"hard",
    question:'______ שלמדתי קשה למבחן, קיבלתי ציון ______.',
    options:["למרות / נמוך","בגלל / נמוך","כי / גבוה","אחרי / יפה"], correct:0,
    explanation:'"למרות" = ניגוד מפתיע. למדתי קשה אבל ציון נמוך.' },
  { id:"2-52",topic:2,grades:[2],difficulty:"hard",
    question:'הספר היה כל כך ______ שלא יכולתי ______ לקרוא.',
    options:["משעמם / להמשיך","מפחיד / להפסיק","מעניין / להפסיק","קל / להתחיל"], correct:2,
    explanation:'ספר מעניין → לא יכולתי להפסיק. ביטוי נפוץ.' },
  { id:"2-53",topic:2,grades:[3, 4],difficulty:"hard",
    question:'ככל שהחידה ______ יותר, כך ______ יותר כשפותרים אותה.',
    options:["קשה / משמח","קלה / קשה","ארוכה / עצוב","מוזרה / מפחיד"], correct:0,
    explanation:'ככל שקשה יותר, כך יותר משמח לפתור - אתגר ותגמול.' },
  { id:"2-54",topic:2,grades:[3],difficulty:"hard",
    question:'לא ______ ולא ______ - פשוט נשארתי במקום.',
    options:["התקדמתי / נסוגתי","אכלתי / שתיתי","צחקתי / בכיתי","עליתי / ירדתי"], correct:0,
    explanation:'לא התקדמתי ולא נסוגתי = נשארתי במקום. ניגודים שלא קרו.' },
  { id:"2-55",topic:2,grades:[4],difficulty:"hard",
    question:'אילו ______, הייתי ______ - אבל זה כבר מאוחר מדי.',
    options:["ידעתי מראש / משנה דעתי","שאלתי / מבין","בדקתי / מוצא","חשבתי / יודע"], correct:0,
    explanation:'"אילו" = תנאי שלא התקיים. חרטה על העבר.' },
  { id:"2-56",topic:2,grades:[4],difficulty:"hard",
    question:'לא ______ היה המצב, כי ______ גרם לשיפור.',
    options:["חסר תקווה / שינוי קטן","טוב / כישלון","ברור / הזמן","נוח / מאמץ"], correct:0,
    explanation:'לא חסר תקווה כי שינוי קטן שיפר. אופטימיות.' },

  // ===== EXTRA QUESTIONS: TOPIC 3 - FRACTIONS (grade 2) =====
  { id:"3-50",topic:3,grades:[2, 3],difficulty:"medium",
    question:"אמא חתכה פיצה ל-4 חלקים שווים. דני אכל חלק אחד. איזה חלק מהפיצה נשאר?",
    options:["חצי","שלושה רבעים","רבע","שני שלישים"], correct:1,
    explanation:"נשאר: 4/4-1/4=3/4 (שלושה רבעים)." },
  { id:"3-51",topic:3,grades:[2, 3],difficulty:"medium",
    question:"שוקולד חולק ל-8 חלקים. נועה אכלה 4. איזה חלק אכלה?",
    options:["רבע","שליש","חצי","שלושה רבעים"], correct:2,
    explanation:"4 מתוך 8 = 4/8 = 1/2 (חצי)." },
  { id:"3-52",topic:3,grades:[2, 3],difficulty:"hard",
    question:"עוגה חולקה ל-6 חלקים. רון אכל 2 ויעל אכלה 1. כמה נשאר?",
    options:["חצי","שליש","רבע","שני שלישים"], correct:0,
    explanation:"אכלו 3 מתוך 6. נשאר: 3/6=1/2 (חצי)." },
  { id:"3-53",topic:3,grades:[2],difficulty:"hard",
    question:"סרגל חולק ל-4 חלקים שווים, כל חלק 5 ס\"מ. מה אורכו?",
    options:["9 ס\"מ","15 ס\"מ","20 ס\"מ","25 ס\"מ"], correct:2,
    explanation:"4×5=20 ס\"מ." },
  { id:"3-54",topic:3,grades:[2],difficulty:"hard",
    question:"בצלחת 12 עוגיות. הילדים אכלו שליש. כמה נשארו?",
    options:["4","6","8","9"], correct:2,
    explanation:"שליש מ-12=4 אכלו. נשאר: 12-4=8." },
  { id:"3-55",topic:3,grades:[2],difficulty:"hard",
    question:"לכל ילד 3 עפרונות ו-2 מחדדים. 8 ילדים בכיתה. כמה פריטים בסה\"כ?",
    options:["24","40","32","48"], correct:1,
    explanation:"8×3=24 עפרונות. 8×2=16 מחדדים. 24+16=40." },
  { id:"3-56",topic:3,grades:[2],difficulty:"hard",
    question:"קניתי 7 שקיות עם 6 סוכריות כל אחת. נתתי 10. כמה נשאר?",
    options:["22","32","38","42"], correct:1,
    explanation:"7×6=42. 42-10=32." },
  // TOPIC 3 - grade 3 extra
  { id:"3-57",topic:3,grades:[3, 4],difficulty:"hard",
    question:"בקופסה 48 כדורים. חצי אדומים, רבע כחולים, השאר ירוקים. כמה ירוקים?",
    options:["6","12","18","24"], correct:1,
    explanation:"אדומים: 24. כחולים: 12. ירוקים: 48-24-12=12." },
  { id:"3-58",topic:3,grades:[3, 4],difficulty:"hard",
    question:"רכבת יוצאת ב-8:15. מגיעה אחרי שעה ו-45 דקות. מתי?",
    options:["9:00","9:45","10:00","10:15"], correct:2,
    explanation:"8:15+1:45=10:00." },
  { id:"3-59",topic:3,grades:[3],difficulty:"hard",
    question:"חניון 5 קומות, 30 מקומות בכל אחת. 87 תפוסים. כמה פנויים?",
    options:["57","63","67","93"], correct:1,
    explanation:"5×30=150. 150-87=63." },
  // TOPIC 3 - grade 4 extra
  { id:"3-60",topic:3,grades:[4],difficulty:"hard",
    question:"הנחה של רבע מהמחיר. חולצה ב-80₪. כמה עולות 3 חולצות אחרי הנחה?",
    options:["120","160","180","240"], correct:2,
    explanation:"הנחה: 80/4=20. מחיר: 60. שלוש: 60×3=180." },
  { id:"3-61",topic:3,grades:[4],difficulty:"hard",
    question:"5 פועלים בונים קיר ב-8 ימים. כמה ייקח ל-10 פועלים?",
    options:["2","4","8","16"], correct:1,
    explanation:"כפול פועלים=חצי זמן. 8÷2=4 ימים." },
  { id:"3-62",topic:3,grades:[4],difficulty:"hard",
    question:"בסדרה: 2, 6, 18, 54... מה הבא?",
    options:["72","108","162","216"], correct:2,
    explanation:"×3: 2,6,18,54,162." },

  // ===== EXTRA QUESTIONS: TOPIC 4 =====
  { id:"4-50",topic:4,grades:[2, 3],difficulty:"medium",
    question:"c_mult3",visual:{type:"circles_trio",circles:[{top:[2,3],bottom:6},{top:[4,2],bottom:8},{top:[3,5],bottom:"?"}]},
    options:["8","10","15","18"], correct:2,
    explanation:"כפל: 2×3=6, 4×2=8, 3×5=15." },
  { id:"4-51",topic:4,grades:[2],difficulty:"hard",
    question:"c_div2",visual:{type:"circles_trio",circles:[{top:[10,2],bottom:5},{top:[12,3],bottom:4},{top:[20,4],bottom:"?"}]},
    options:["3","5","16","24"], correct:1,
    explanation:"חילוק: 10÷2=5, 12÷3=4, 20÷4=5." },
  { id:"4-52",topic:4,grades:[2],difficulty:"hard",
    question:"seq_x3",visual:{type:"sequence",numbers:[1,3,9,27,"?"]},
    options:["36","54","81","108"], correct:2,
    explanation:"×3: 1,3,9,27,81." },
  { id:"4-53",topic:4,grades:[3, 4],difficulty:"hard",
    question:"c_mp1",visual:{type:"circles_trio",circles:[{top:[2,3],bottom:7},{top:[4,2],bottom:9},{top:[3,5],bottom:"?"}]},
    options:["8","15","16","17"], correct:2,
    explanation:"כפל+1: 2×3+1=7, 4×2+1=9, 3×5+1=16." },
  { id:"4-54",topic:4,grades:[3],difficulty:"hard",
    question:"seq_fib",visual:{type:"sequence",numbers:[1,1,2,3,5,8,"?"]},
    options:["10","11","13","16"], correct:2,
    explanation:"פיבונאצ'י: כל מספר=סכום שני הקודמים. 5+8=13." },
  { id:"4-55",topic:4,grades:[3],difficulty:"hard",
    question:"c_sq",visual:{type:"circles_trio",circles:[{top:[2,3],bottom:13},{top:[3,4],bottom:25},{top:[1,5],bottom:"?"}]},
    options:["6","10","26","30"], correct:2,
    explanation:"ריבועים: 2²+3²=4+9=13, 3²+4²=25, 1²+5²=26." },
  { id:"4-56",topic:4,grades:[4],difficulty:"hard",
    question:"c_cubed",visual:{type:"circles_trio",circles:[{top:[2,1],bottom:9},{top:[3,2],bottom:29},{top:[4,1],bottom:"?"}]},
    options:["17","33","65","81"], correct:2,
    explanation:"מעוקבים: 2³+1=9, 3³+2=29, 4³+1=65." },
  { id:"4-57",topic:4,grades:[4],difficulty:"hard",
    question:"tr2",visual:{type:"triangle_pyramid",numbers:{top:120,midLeft:40,midRight:"?",botLeft:8,botMid:5,botRight:16}},
    options:["64","80","96","100"], correct:1,
    explanation:"כפל: 8×5=40, 5×16=80. 40+80=120 ✓. ?=80." },
  { id:"4-58",topic:4,grades:[4],difficulty:"hard",
    question:"seq_prime",visual:{type:"sequence",numbers:[2,3,5,7,11,13,"?"]},
    options:["15","16","17","19"], correct:2,
    explanation:"ראשוניים: 2,3,5,7,11,13,17." },

  // --- Varied ? positions ---
  { id:"4-60",topic:4,grades:[2,3],difficulty:"medium",
    question:"c_top_missing",visual:{type:"circles_trio",circles:[{top:[6,4],bottom:10},{top:["?",3],bottom:12},{top:[5,2],bottom:7}]},
    options:["6","8","9","15"], correct:2,
    explanation:"סכום: 6+4=10, ?+3=12 → ?=9, 5+2=7." },
  { id:"4-61",topic:4,grades:[2,3],difficulty:"medium",
    question:"c_top2_missing",visual:{type:"circles_trio",circles:[{top:[3,5],bottom:15},{top:[4,"?"],bottom:24},{top:[2,7],bottom:14}]},
    options:["4","6","8","20"], correct:1,
    explanation:"כפל: 3×5=15, 4×?=24 → ?=6, 2×7=14." },
  { id:"4-62",topic:4,grades:[3,4],difficulty:"hard",
    question:"c_top_hard",visual:{type:"circles_trio",circles:[{top:[8,2],bottom:6},{top:[15,5],bottom:10},{top:["?",4],bottom:7}]},
    options:["3","11","14","28"], correct:1,
    explanation:"חיסור: 8-2=6, 15-5=10, ?-4=7 → ?=11." },
  { id:"4-63",topic:4,grades:[3,4],difficulty:"hard",
    question:"tri_mid",visual:{type:"triangle_pyramid",numbers:{top:30,midLeft:"?",midRight:12,botLeft:6,botMid:3,botRight:4}},
    options:["12","15","18","24"], correct:2,
    explanation:"כפל: 6×3=18, 3×4=12. למעלה: 18+12=30 ✓. ?=18." },
  { id:"4-64",topic:4,grades:[3,4],difficulty:"hard",
    question:"tri_bot",visual:{type:"triangle_pyramid",numbers:{top:24,midLeft:13,midRight:11,botLeft:8,botMid:"?",botRight:6}},
    options:["3","5","7","10"], correct:1,
    explanation:"הכלל: כל מספר = סכום שניים מתחתיו. midL=botL+botMid: 8+?=13 → ?=5. בדיקה: midR=botMid+botRight: 5+6=11 ✓. top=midL+midR: 13+11=24 ✓." },
  { id:"4-65",topic:4,grades:[2,3],difficulty:"medium",
    question:"c_bottom_mult_varied",visual:{type:"circles_trio",circles:[{top:[3,"?"],bottom:15},{top:[4,3],bottom:12},{top:[6,2],bottom:12}]},
    options:["3","4","5","12"], correct:2,
    explanation:"כפל: 3×?=15 → ?=5. 4×3=12 ✓, 6×2=12 ✓." },

  // ===== EXTRA QUESTIONS: TOPIC 5 =====
  { id:"5-50",topic:5,grades:[2, 3],difficulty:"medium",
    question:"three_cycle",
    visual:{type:"shape_row",sequence:[
      {shape:"circle",stroke:"#22d3ee"},{shape:"triangle",stroke:"#22d3ee"},{shape:"square",stroke:"#22d3ee"},
      {shape:"circle",stroke:"#22d3ee"},{shape:"triangle",stroke:"#22d3ee"}
    ]},
    options:[{shape:"square",stroke:"#22d3ee"},{shape:"circle",stroke:"#22d3ee"},{shape:"triangle",stroke:"#22d3ee"},{shape:"diamond",stroke:"#22d3ee"}],
    correct:0,
    explanation:"מחזור: עיגול,משולש,ריבוע חוזר. הבא: ריבוע." },
  { id:"5-51",topic:5,grades:[2],difficulty:"hard",
    question:"thick_lines",
    visual:{type:"shape_row",sequence:[
      {shape:"square",stroke:"#f87171",strokeWidth:1.5},
      {shape:"square",stroke:"#f87171",strokeWidth:2.5},
      {shape:"square",stroke:"#f87171",strokeWidth:4}
    ]},
    options:[{shape:"square",stroke:"#f87171",strokeWidth:5.5},{shape:"square",stroke:"#f87171",strokeWidth:1.5},{shape:"circle",stroke:"#f87171",strokeWidth:5.5},{shape:"square",stroke:"#60a5fa",strokeWidth:5.5}],
    correct:0,
    explanation:"הקווים מתעבים. ריבוע עם קו עבה יותר." },
  { id:"5-52",topic:5,grades:[3, 4],difficulty:"hard",
    question:"mat_fill",
    visual:{type:"matrix_3x3",grid:[
      [{shape:"circle",stroke:"#f87171",fill:"#f87171"},{shape:"circle",stroke:"#f87171",fill:"none"},{shape:"circle",stroke:"#f87171",fill:"rgba(248,113,113,0.4)"}],
      [{shape:"square",stroke:"#60a5fa",fill:"none"},{shape:"square",stroke:"#60a5fa",fill:"rgba(96,165,250,0.4)"},{shape:"square",stroke:"#60a5fa",fill:"#60a5fa"}],
      [{shape:"triangle",stroke:"#4ade80",fill:"rgba(74,222,128,0.4)"},{shape:"triangle",stroke:"#4ade80",fill:"#4ade80"},null]
    ]},
    options:[{shape:"triangle",stroke:"#4ade80",fill:"none"},{shape:"triangle",stroke:"#4ade80",fill:"#4ade80"},{shape:"triangle",stroke:"#4ade80",fill:"rgba(74,222,128,0.4)"},{shape:"square",stroke:"#4ade80",fill:"none"}],
    correct:0,
    explanation:"בכל שורה: 3 מצבי מילוי בסדר שונה. שורה 3: חצי,מלא → חסר ריק." },
  { id:"5-53",topic:5,grades:[4],difficulty:"hard",
    question:"mat_multi",
    visual:{type:"matrix_3x3",grid:[
      [{shape:"circle",stroke:"#f87171",fill:"none"},{shape:"square",stroke:"#60a5fa",fill:"#60a5fa"},{shape:"triangle",stroke:"#4ade80",fill:"none"}],
      [{shape:"square",stroke:"#4ade80",fill:"#4ade80"},{shape:"triangle",stroke:"#f87171",fill:"none"},{shape:"circle",stroke:"#60a5fa",fill:"#60a5fa"}],
      [{shape:"triangle",stroke:"#60a5fa",fill:"none"},{shape:"circle",stroke:"#4ade80",fill:"#4ade80"},null]
    ]},
    options:[{shape:"square",stroke:"#f87171",fill:"none"},{shape:"square",stroke:"#f87171",fill:"#f87171"},{shape:"circle",stroke:"#f87171",fill:"#f87171"},{shape:"diamond",stroke:"#f87171",fill:"none"}],
    correct:0,
    explanation:"בכל שורה/עמודה: כל צורה פעם, כל צבע פעם. חסר: ריבוע אדום ריק." },
  { id:"5-54",topic:5,grades:[4],difficulty:"hard",
    question:"mat_dots",
    visual:{type:"matrix_3x3",grid:[
      [{shape:"circle",stroke:"#818cf8",dot:"top",dotColor:"#fbbf24"},{shape:"circle",stroke:"#818cf8",dot:"right",dotColor:"#fbbf24"},{shape:"circle",stroke:"#818cf8",dot:"bottom",dotColor:"#fbbf24"}],
      [{shape:"square",stroke:"#818cf8",dot:"right",dotColor:"#fbbf24"},{shape:"square",stroke:"#818cf8",dot:"bottom",dotColor:"#fbbf24"},{shape:"square",stroke:"#818cf8",dot:"left",dotColor:"#fbbf24"}],
      [{shape:"triangle",stroke:"#818cf8",dot:"bottom",dotColor:"#fbbf24"},{shape:"triangle",stroke:"#818cf8",dot:"left",dotColor:"#fbbf24"},null]
    ]},
    options:[
      {shape:"triangle",stroke:"#818cf8",dot:"top",dotColor:"#fbbf24"},
      {shape:"triangle",stroke:"#818cf8",dot:"right",dotColor:"#fbbf24"},
      {shape:"triangle",stroke:"#818cf8",dot:"center",dotColor:"#fbbf24"},
      {shape:"circle",stroke:"#818cf8",dot:"top",dotColor:"#fbbf24"}
    ],
    correct:0,
    explanation:"צורה: שורה=זהה. נקודה: מסתובבת בכיוון השעון. שורה 3: למטה→שמאל→למעלה." },

  // ===== QUESTIONS FROM MATIC TEST =====
  // Topic 1 - Analogies
  { id:"1-70",topic:1,grades:[2,3],difficulty:"medium",
    question:"מקלדת : להקיש", options:["אופניים : לדווש","מנורה : להאיר","רמקול : להגביר","ספר : לכתוב"], correct:0,
    explanation:"הקשר: מכשיר והפעולה הפיזית שעושים איתו. מקלדת - מקישים עליה, אופניים - דוושים עליהם. מנורה מאירה (לא הפעולה שלנו), רמקול מגביר (פעולה של המכשיר)." },
  { id:"1-71",topic:1,grades:[2,3],difficulty:"hard",
    question:"את (כלי חפירה) : חפירה", options:["שולחן : כתיבה","מנורה : הדלקה","אטב : הצמדה","דלת : פתיחה"], correct:2,
    explanation:"הקשר: כלי קטן והפעולה הספציפית שעושים איתו. את לחפירה, אטב להצמדה. שולחן לא כלי, מנורה - הדלקה זו פעולה כללית, דלת - לא כלי." },
  { id:"1-72",topic:1,grades:[2,3,4],difficulty:"hard",
    question:"נעל : סנדלר", options:["חוט : חייט","צלחת : טבח","משרד : פקיד","פרסה : נפח"], correct:3,
    explanation:"הקשר: מוצר ובעל המלאכה שמכין אותו. סנדלר מכין נעליים, נפח מכין פרסות (לסוסים). חייט עובד עם בד (לא חוט), טבח לא מכין צלחת, פקיד לא מכין משרד." },

  // Topic 2 - Sentence completion
  { id:"2-70",topic:2,grades:[2,3],difficulty:"hard",
    question:'דני אמר: "חסכתי לטיול ______ הכסף לא הספיק ולכן בסוף ______ לטיול."',
    options:["למרות ש / לא נסעתי","כמו ש / נסעתי","אך / לא נסעתי","כי / נסעתי"], correct:2,
    explanation:'"אך" מציין ניגוד: חסכתי אך הכסף לא הספיק, ולכן לא נסעתי. "למרות ש" לא מתאים כי אחריו צריך "עדיין נסעתי".' },
  { id:"2-71",topic:2,grades:[3,4],difficulty:"hard",
    question:'לאחי יש ______ והוא ______.',
    options:["דוד / האחיין שלי","בן / האחיין שלי","נכד / סבא","אח / גיסי"], correct:1,
    explanation:'אם לאחי יש בן, אז הבן הזה הוא האחיין שלי. דוד הוא אח של הורה, נכד וסבא - הכיוון הפוך, אח וגיסי - גיס הוא בעל של אחות.' },
  { id:"2-72",topic:2,grades:[2,3],difficulty:"hard",
    question:'למדתי לספור ______ אנגלית ______ בספרדית.',
    options:["אך ורק / ורק","אך ורק / ולא","גם / ורק","גם / ולא"], correct:1,
    explanation:'"אך ורק באנגלית ולא בספרדית" - הגיוני. למד רק שפה אחת ולא את השנייה.' },

  // Topic 3 - Word problems
  { id:"3-70",topic:3,grades:[2,3],difficulty:"medium",
    question:"במטוס 25 שורות. בכל שורה 6 כסאות. יש גם 2 כסאות לטייס ולטייס המשנה. כמה כסאות יש בסך הכל?",
    options:["152","33","56","300"], correct:0,
    explanation:"25×6=150 כסאות נוסעים + 2 לטייסים = 152." },
  { id:"3-71",topic:3,grades:[2,3,4],difficulty:"hard",
    question:"במכולת 56 קרטוני חלב. המוכר חילק אותם שווה ל-8 ארגזים. אתמול מכר 3 ארגזים שלמים. כמה קרטונים מכר?",
    options:["7","21","32","16"], correct:1,
    explanation:"56÷8=7 קרטונים בכל ארגז. מכר 3 ארגזים: 3×7=21." },
  { id:"3-72",topic:3,grades:[3,4],difficulty:"hard",
    question:"יוסי בחר מספר אי-זוגי דו-ספרתי. ספרת העשרות גדולה ב-4 מספרת האחדות. סכום הספרות הוא 10. מהו?",
    options:["37","51","62","73"], correct:3,
    explanation:"אם אחדות=x, עשרות=x+4. x+(x+4)=10, 2x=6, x=3. המספר: 73. בדיקה: 7-3=4 ✓, 7+3=10 ✓, 73 אי-זוגי ✓." },

  // Topic 4 - Star shape & new patterns
  { id:"4-70",topic:4,grades:[2,3,4],difficulty:"hard",
    question:"star_squared",
    visual:{type:"star_numbers",
      outer:[49,36,"?",25,16],
      inner:[7,6,8,5,4]
    },
    options:["64","72","65","73"], correct:0,
    explanation:"הכלל: כל מספר חיצוני = ריבוע של המספר הפנימי שמולו. 7²=49, 6²=36, 5²=25, 4²=16. אז 8²=64." },
  { id:"4-71",topic:4,grades:[2,3],difficulty:"medium",
    question:"star_sum",
    visual:{type:"star_numbers",
      outer:[11,9,"?",8,7],
      inner:[5,3,6,2,1]
    },
    options:["10","12","14","18"], correct:1,
    explanation:"הכלל: חיצוני = פנימי×2. 5×2+1=11? לא. ננסה: חיצוני = פנימי+6: 5+6=11, 3+6=9, 2+6=8, 1+6=7. אז 6+6=12." },
  { id:"4-72",topic:4,grades:[3,4],difficulty:"hard",
    question:"star_mult",
    visual:{type:"star_numbers",
      outer:[30,18,"?",12,24],
      inner:[5,3,7,2,4]
    },
    options:["35","42","49","56"], correct:1,
    explanation:"הכלל: חיצוני = פנימי × 6. 5×6=30, 3×6=18, 2×6=12, 4×6=24. אז 7×6=42." },
  { id:"4-73",topic:4,grades:[2,3],difficulty:"medium",
    question:"arrows_div",
    visual:{type:"squares_arrows",rows:[{left:8,center:7,right:56},{left:9,center:"?",right:54}]},
    options:["6","5","7","3"], correct:0,
    explanation:"הכלל: ימין ÷ אמצע = שמאל. 56÷7=8, 54÷?=9 → ?=6." },
  { id:"4-74",topic:4,grades:[3,4],difficulty:"hard",
    question:"tri_matic",
    visual:{type:"triangle_pyramid",numbers:{top:"?",midLeft:7,midRight:12,botLeft:14,botMid:21,botRight:33}},
    options:["21","19","5","45"], correct:2,
    explanation:"הכלל: כל מספר למעלה = ההפרש בין שניים מתחתיו. 21-14=7, 33-21=12. top: 12-7=5." },

  // More pyramids
  { id:"4-80",topic:4,grades:[2,3],difficulty:"medium",
    question:"tri_sum_simple",visual:{type:"triangle_pyramid",numbers:{top:15,midLeft:"?",midRight:8,botLeft:4,botMid:3,botRight:5}},
    options:["5","7","9","12"], correct:1,
    explanation:"סכום: botL+botM=midL: 4+3=7. botM+botR=midR: 3+5=8 ✓. midL+midR=top: 7+8=15 ✓." },
  { id:"4-81",topic:4,grades:[3,4],difficulty:"hard",
    question:"tri_mult",visual:{type:"triangle_pyramid",numbers:{top:72,midLeft:18,midRight:"?",botLeft:3,botMid:6,botRight:4}},
    options:["12","24","36","54"], correct:1,
    explanation:"כפל: 3×6=18, 6×4=24. top=midL×midR? 18×24=432≠72. ננסה: top=midL+midR+30? top=botL×botM×botR? 3×6×4=72 ✓ כלל: למעלה=מכפלת כל התחתונים. ?=6×4=24." },
  { id:"4-82",topic:4,grades:[2,3],difficulty:"medium",
    question:"tri_diff_bot",visual:{type:"triangle_pyramid",numbers:{top:20,midLeft:12,midRight:8,botLeft:6,botMid:"?",botRight:2}},
    options:["4","6","8","10"], correct:1,
    explanation:"סכום: botL+botM=midL: 6+?=12 → ?=6. בדיקה: botM+botR=midR: 6+2=8 ✓. top=12+8=20 ✓." },
  { id:"4-83",topic:4,grades:[3,4],difficulty:"hard",
    question:"tri_botright",visual:{type:"triangle_pyramid",numbers:{top:35,midLeft:15,midRight:20,botLeft:5,botMid:10,botRight:"?"}},
    options:["5","10","15","20"], correct:1,
    explanation:"סכום: 5+10=15 ✓, 10+?=20 → ?=10. top: 15+20=35 ✓." },

  // More stars
  { id:"4-84",topic:4,grades:[2,3],difficulty:"medium",
    question:"star_double",visual:{type:"star_numbers",outer:[10,12,"?",8,14],inner:[5,6,4,4,7]},
    options:["6","8","12","16"], correct:1,
    explanation:"חיצוני = פנימי × 2. 5×2=10, 6×2=12, 4×2=8, 7×2=14. ?=4×2=8." },
  { id:"4-85",topic:4,grades:[3,4],difficulty:"hard",
    question:"star_add_inner",visual:{type:"star_numbers",outer:[12,11,"?",7,9],inner:[7,6,8,2,4]},
    options:["10","12","13","15"], correct:2,
    explanation:"חיצוני = פנימי + 5. 7+5=12, 6+5=11, 2+5=7, 4+5=9. ?=8+5=13." },
  { id:"4-86",topic:4,grades:[3,4],difficulty:"hard",
    question:"star_cubes",visual:{type:"star_numbers",outer:[27,8,"?",1,64],inner:[3,2,4,1,4]},
    options:["16","48","64","81"], correct:2,
    explanation:"חיצוני = פנימי³. 3³=27, 2³=8, 1³=1, 4³=64. ?=4³=64." },
  { id:"4-87",topic:4,grades:[2,3,4],difficulty:"hard",
    question:"star_matic",visual:{type:"star_numbers",outer:[49,36,"?",25,16],inner:[7,6,8,5,4]},
    options:["64","72","65","73"], correct:0,
    explanation:"חיצוני = פנימי². 7²=49, 6²=36, 5²=25, 4²=16. ?=8²=64." },

  // More arrows
  { id:"4-88",topic:4,grades:[2,3],difficulty:"medium",
    question:"arr_add",visual:{type:"squares_arrows",rows:[{left:15,center:3,right:5},{left:24,center:"?",right:8}]},
    options:["2","3","4","16"], correct:1,
    explanation:"שמאל = אמצע × ימין. 3×5=15, ?×8=24 → ?=3." },
  { id:"4-89",topic:4,grades:[3,4],difficulty:"hard",
    question:"arr_square",visual:{type:"squares_arrows",rows:[{left:25,center:5,right:5},{left:49,center:7,right:7},{left:"?",center:9,right:9}]},
    options:["18","36","81","99"], correct:2,
    explanation:"שמאל = אמצע × ימין (ריבוע). 5×5=25, 7×7=49, 9×9=81." },
  { id:"4-90",topic:4,grades:[2,3],difficulty:"medium",
    question:"arr_matic",visual:{type:"squares_arrows",rows:[{left:8,center:7,right:56},{left:9,center:"?",right:54}]},
    options:["6","5","7","3"], correct:0,
    explanation:"ימין ÷ אמצע = שמאל. 56÷7=8, 54÷?=9 → ?=6." },
  { id:"4-91",topic:4,grades:[3,4],difficulty:"hard",
    question:"arr_complex",visual:{type:"squares_arrows",rows:[{left:10,center:3,right:7},{left:15,center:4,right:11},{left:"?",center:5,right:13}]},
    options:["8","15","18","65"], correct:2,
    explanation:"שמאל = ימין + אמצע. 7+3=10, 11+4=15, 13+5=18." },

  // ===== COMPLEX VISUAL PATTERNS (Matic Q13/Q15 style) =====
  // Q13 style - Symbol counting patterns
  { id:"5-60",topic:5,grades:[2,3],difficulty:"hard",
    question:"symbol_count_row",
    visual:{type:"symbol_row",sequence:[
      {symbols:[{char:"♥",count:5,color:"#f87171",size:9},{char:"+",count:4,color:"#e2e8f0",size:9},{char:"◆",count:1,color:"#fbbf24",size:8}]},
      {symbols:[{char:"♥",count:5,color:"#f87171",size:9},{char:"+",count:3,color:"#e2e8f0",size:9},{char:"◆",count:2,color:"#fbbf24",size:8}]},
      {symbols:[{char:"♥",count:5,color:"#f87171",size:9},{char:"+",count:2,color:"#e2e8f0",size:9},{char:"◆",count:3,color:"#fbbf24",size:8}]},
      {symbols:[{char:"♥",count:5,color:"#f87171",size:9},{char:"+",count:1,color:"#e2e8f0",size:9},{char:"◆",count:4,color:"#fbbf24",size:8}]}
    ]},
    options:[
      {type:"symbols",symbols:[{char:"♥",count:5,color:"#f87171",size:9},{char:"+",count:2,color:"#e2e8f0",size:9},{char:"◆",count:5,color:"#fbbf24",size:8}]},
      {type:"symbols",symbols:[{char:"♥",count:5,color:"#f87171",size:9},{char:"◆",count:5,color:"#fbbf24",size:8}]},
      {type:"symbols",symbols:[{char:"♥",count:4,color:"#f87171",size:9},{char:"+",count:1,color:"#e2e8f0",size:9},{char:"◆",count:5,color:"#fbbf24",size:8}]},
      {type:"symbols",symbols:[{char:"♥",count:5,color:"#f87171",size:9},{char:"◆",count:4,color:"#fbbf24",size:8},{char:"+",count:1,color:"#e2e8f0",size:9}]}
    ],
    correct:1,
    explanation:"הכלל: ♥ תמיד 5. + יורד ב-1 כל פעם (4,3,2,1,0). ◆ עולה ב-1 (1,2,3,4,5). הבא: 5 לבבות, 0 פלוסים, 5 יהלומים." },

  { id:"5-61",topic:5,grades:[2,3,4],difficulty:"hard",
    question:"symbol_count_row2",
    visual:{type:"symbol_row",sequence:[
      {symbols:[{char:"★",count:4,color:"#fbbf24",size:10},{char:"●",count:1,color:"#60a5fa",size:10}]},
      {symbols:[{char:"★",count:3,color:"#fbbf24",size:10},{char:"●",count:2,color:"#60a5fa",size:10}]},
      {symbols:[{char:"★",count:2,color:"#fbbf24",size:10},{char:"●",count:3,color:"#60a5fa",size:10}]}
    ]},
    options:[
      {type:"symbols",symbols:[{char:"★",count:1,color:"#fbbf24",size:10},{char:"●",count:4,color:"#60a5fa",size:10}]},
      {type:"symbols",symbols:[{char:"★",count:0,color:"#fbbf24",size:10},{char:"●",count:5,color:"#60a5fa",size:10}]},
      {type:"symbols",symbols:[{char:"★",count:2,color:"#fbbf24",size:10},{char:"●",count:2,color:"#60a5fa",size:10}]},
      {type:"symbols",symbols:[{char:"★",count:1,color:"#fbbf24",size:10},{char:"●",count:3,color:"#60a5fa",size:10}]}
    ],
    correct:0,
    explanation:"★ יורד ב-1 (4,3,2,1). ● עולה ב-1 (1,2,3,4). סה\"כ תמיד 5." },

  // Q15 style - Pacman + color matrix
  { id:"5-62",topic:5,grades:[3,4],difficulty:"hard",
    question:"pacman_matrix",
    visual:{type:"matrix_3x3",grid:[
      [{type:"pacman",rotation:315,fill:"#94a3b8"},{type:"rect_fill",fill:"#1e293b"},{type:"pacman_rect",rotation:135,pacFill:"#e2e8f0",rectFill:"#1e293b"}],
      [{type:"pacman",rotation:225,fill:"#64748b"},{type:"rect_fill",fill:"#64748b"},{type:"pacman_rect",rotation:45,pacFill:"#94a3b8",rectFill:"#64748b"}],
      [{type:"pacman",rotation:135,fill:"#cbd5e1"},{type:"rect_fill",fill:"#cbd5e1"},null]
    ]},
    options:[
      {type:"pacman_rect",rotation:315,pacFill:"#e2e8f0",rectFill:"#cbd5e1"},
      {type:"pacman_rect",rotation:135,pacFill:"#cbd5e1",rectFill:"#94a3b8"},
      {type:"pacman_rect",rotation:225,pacFill:"#e2e8f0",rectFill:"#cbd5e1"},
      {type:"pacman_rect",rotation:315,pacFill:"#cbd5e1",rectFill:"#e2e8f0"}
    ],
    correct:0,
    explanation:"3 כללים: 1) עמודה 1=פקמן, עמודה 2=ריבוע, עמודה 3=שניהם. 2) צבע הולך ובהיר כלפי מטה. 3) כיוון הפקמן מסתובב. חסר: פקמן+ריבוע בגוון בהיר." },

  // Pacman rotation sequence
  { id:"5-63",topic:5,grades:[2,3],difficulty:"medium",
    question:"pacman_rotate",
    visual:{type:"shape_row",sequence:[
      {type:"pacman",rotation:0,fill:"#fbbf24"},
      {type:"pacman",rotation:90,fill:"#fbbf24"},
      {type:"pacman",rotation:180,fill:"#fbbf24"},
      {type:"pacman",rotation:270,fill:"#fbbf24"}
    ]},
    options:[
      {type:"pacman",rotation:0,fill:"#fbbf24"},
      {type:"pacman",rotation:45,fill:"#fbbf24"},
      {type:"pacman",rotation:90,fill:"#fbbf24"},
      {type:"pacman",rotation:180,fill:"#fbbf24"}
    ],
    correct:0,
    explanation:"הפקמן מסתובב 90° בכל פעם: ימין→למטה→שמאל→למעלה→ימין (חוזר)." },

  // Symbol double change pattern
  { id:"5-64",topic:5,grades:[3,4],difficulty:"hard",
    question:"symbol_double_change",
    visual:{type:"symbol_row",sequence:[
      {symbols:[{char:"▲",count:1,color:"#f87171",size:12},{char:"■",count:3,color:"#60a5fa",size:10}]},
      {symbols:[{char:"▲",count:2,color:"#f87171",size:12},{char:"■",count:2,color:"#60a5fa",size:10}]},
      {symbols:[{char:"▲",count:3,color:"#f87171",size:12},{char:"■",count:1,color:"#60a5fa",size:10}]}
    ]},
    options:[
      {type:"symbols",symbols:[{char:"▲",count:4,color:"#f87171",size:12}]},
      {type:"symbols",symbols:[{char:"▲",count:4,color:"#f87171",size:12},{char:"■",count:1,color:"#60a5fa",size:10}]},
      {type:"symbols",symbols:[{char:"▲",count:3,color:"#f87171",size:12},{char:"■",count:2,color:"#60a5fa",size:10}]},
      {type:"symbols",symbols:[{char:"■",count:4,color:"#60a5fa",size:10}]}
    ],
    correct:0,
    explanation:"▲ עולה ב-1 (1,2,3,4). ■ יורד ב-1 (3,2,1,0). הבא: 4 משולשים בלבד." },

  // Color gradient pacman matrix
  { id:"5-65",topic:5,grades:[3,4],difficulty:"hard",
    question:"pacman_color_matrix",
    visual:{type:"matrix_3x3",grid:[
      [{type:"pacman",rotation:0,fill:"#f87171"},{type:"pacman",rotation:90,fill:"#f87171"},{type:"pacman",rotation:180,fill:"#f87171"}],
      [{type:"pacman",rotation:0,fill:"#60a5fa"},{type:"pacman",rotation:90,fill:"#60a5fa"},{type:"pacman",rotation:180,fill:"#60a5fa"}],
      [{type:"pacman",rotation:0,fill:"#4ade80"},{type:"pacman",rotation:90,fill:"#4ade80"},null]
    ]},
    options:[
      {type:"pacman",rotation:180,fill:"#4ade80"},
      {type:"pacman",rotation:270,fill:"#4ade80"},
      {type:"pacman",rotation:0,fill:"#4ade80"},
      {type:"pacman",rotation:180,fill:"#fbbf24"}
    ],
    correct:0,
    explanation:"שורות: אותו צבע (אדום, כחול, ירוק). עמודות: אותו סיבוב (0°, 90°, 180°). חסר: פקמן ירוק 180°." },

  // =================== IMAGE-BASED QUESTIONS ===================
  { id:"5-93",topic:5,grades:[2,3],difficulty:"medium",type:"image",
    imagePath:"visual-questions/5-93",
    question:"מה הבא בסדרה?",
    options:["1","2","3","4"], correct:3,
    explanation:"בכל תיבה: הלבבות יורדים ב-1, הפלוסים יורדים ב-1, והכוכבים עולים ב-1. התיבה הבאה: 1 לב, 0 פלוסים, 5 כוכבים." },
  { id:"5-94",topic:5,grades:[2,3],difficulty:"hard",type:"image",
    imagePath:"visual-questions/5-94",
    question:"מה חסר במטריצה?",
    options:["1","2","3","4"], correct:3,
    explanation:"בכל שורה ועמודה, הצורות משתלבות זו בזו. השורה השלישית משלבת את דפוסי החיצים עם דפוסי הקווים." },
  { id:"5-95",topic:5,grades:[2,3],difficulty:"hard",type:"image",
    imagePath:"visual-questions/5-95",
    question:"מה חסר במטריצה?",
    options:["1","2","3","4"], correct:0,
    explanation:"עמודה 1: פקמן מסתובב. עמודה 2: ריבוע בהיר יותר בכל שורה. עמודה 3: שילוב של פקמן+ריבוע. בשורה 3: פקמן קטן, ריבוע בהיר, השילוב שלהם." }
,
  { id:"5-96",topic:5,grades:[2,3],difficulty:"hard",type:"image",
    imagePath:"visual-questions/5-96",
    question:"קרא את השאלה וענה על התשובה הנכונה",
    options:["1","2","3","4"], correct:3,
    explanation:"לא יודע איך להסביר אורי יא נסיך" },
];
